// MIDI NOTE constants

export const djScratch = 29;
export const acousticBassDrum = 35;
export const kick = acousticBassDrum;
export const bassDrum1 = 36;
export const bassDrum = bassDrum1;
export const sideStick = 37;
export const acousticSnare = 38;
export const handClap = 39;
export const electricSnare = 40;
export const snare = electricSnare;
export const lowFloorTom = 41;
export const closedHiHat = 42;
export const highFloorTom = 43;
export const pedalHiHat = 44;
export const lowTom = 45;
export const tom = lowTom;
export const openHiHat = 46;
export const lowMidTom = 47;
export const hiMidTom = 48;
export const crashCymbal = 49;
export const crash = crashCymbal;
export const hiTom = 50;
export const rideCymbal1 = 51;
export const cymbal = rideCymbal1;
export const chineseCymbal = 52;
export const rideBell = 53;
export const tambourine = 54;
export const splashCymbal = 55;
export const cowbell = 56;
export const crashCymbal2 = 57;
export const vibraslap = 58;
export const rideCymbal2 = 59;
export const hiBongo = 60;
export const lowBongo = 61;
export const muteHiConga = 62;
export const openHiConga = 63;
export const lowConga = 64;
export const hiTimbale = 65;
export const lowTimbale = 66;
export const hiAgogo = 67;
export const lowAgogo = 68;
export const cabasa = 69;
export const maracas = 70;
export const shortWhistle = 71;
export const longWhistle = 72;
export const shortGuiro = 73;
export const longGuiro = 74;
export const claves = 75;
export const hiWoodBlock = 76;
export const lowWoodBlock = 77;
export const muteCuica = 78;
export const openCuica = 79;
export const muteTriangle = 80;
export const openTriangle = 81;

export function notes(start: number): number[] {
    let l = [];
    for (let i = start; i < 127; i += 12) l.push(i);
    return l;
}

export const C = notes(0);
export const C0 = C[1],
    C1 = C[2],
    C2 = C[3],
    C3 = C[4],
    C4 = C[5],
    C5 = C[6],
    C6 = C[7],
    C7 = C[8],
    C8 = C[9],
    Cm1 = C[0];
export const Cs = notes(1);
export const Cs0 = Cs[1],
    Cs1 = Cs[2],
    Cs2 = Cs[3],
    Cs3 = Cs[4],
    Cs4 = Cs[5],
    Cs5 = Cs[6],
    Cs6 = Cs[7],
    Cs7 = Cs[8],
    Cs8 = Cs[9],
    Csm1 = Cs[0];
export const Db = Cs;
export const Db0 = Db[1],
    Db1 = Db[2],
    Db2 = Db[3],
    Db3 = Db[4],
    Db4 = Db[5],
    Db5 = Db[6],
    Db6 = Db[7],
    Db7 = Db[8],
    Db8 = Db[9],
    Dbm1 = Db[0];
export const D = notes(2);
export const D0 = D[1],
    D1 = D[2],
    D2 = D[3],
    D3 = D[4],
    D4 = D[5],
    D5 = D[6],
    D6 = D[7],
    D7 = D[8],
    D8 = D[9],
    Dm1 = D[0];
export const Ds = notes(3);
export const Ds0 = Ds[1],
    Ds1 = Ds[2],
    Ds2 = Ds[3],
    Ds3 = Ds[4],
    Ds4 = Ds[5],
    Ds5 = Ds[6],
    Ds6 = Ds[7],
    Ds7 = Ds[8],
    Ds8 = Ds[9],
    Dsm1 = Ds[0];
export const Eb = Ds;
export const Eb0 = Eb[1],
    Eb1 = Eb[2],
    Eb2 = Eb[3],
    Eb3 = Eb[4],
    Eb4 = Eb[5],
    Eb5 = Eb[6],
    Eb6 = Eb[7],
    Eb7 = Eb[8],
    Eb8 = Eb[9],
    Ebm1 = Eb[0];
export const E = notes(4);
export const E0 = E[1],
    E1 = E[2],
    E2 = E[3],
    E3 = E[4],
    E4 = E[5],
    E5 = E[6],
    E6 = E[7],
    E7 = E[8],
    E8 = E[9],
    Em1 = E[0];
export const Es = notes(5);
export const Es0 = Es[1],
    Es1 = Es[2],
    Es2 = Es[3],
    Es3 = Es[4],
    Es4 = Es[5],
    Es5 = Es[6],
    Es6 = Es[7],
    Es7 = Es[8],
    Es8 = Es[9],
    Esm1 = Es[0];
export const F = Es;
export const F0 = F[1],
    F1 = F[2],
    F2 = F[3],
    F3 = F[4],
    F4 = F[5],
    F5 = F[6],
    F6 = F[7],
    F7 = F[8],
    F8 = F[9],
    Fm1 = F[0];
export const Fs = notes(6);
export const Fs0 = Fs[1],
    Fs1 = Fs[2],
    Fs2 = Fs[3],
    Fs3 = Fs[4],
    Fs4 = Fs[5],
    Fs5 = Fs[6],
    Fs6 = Fs[7],
    Fs7 = Fs[8],
    Fs8 = Fs[9],
    Fsm1 = Fs[0];
export const Gb = Fs;
export const Gb0 = Gb[1],
    Gb1 = Gb[2],
    Gb2 = Gb[3],
    Gb3 = Gb[4],
    Gb4 = Gb[5],
    Gb5 = Gb[6],
    Gb6 = Gb[7],
    Gb7 = Gb[8],
    Gb8 = Gb[9],
    Gbm1 = Gb[0];
export const G = notes(7);
export const G0 = G[1],
    G1 = G[2],
    G2 = G[3],
    G3 = G[4],
    G4 = G[5],
    G5 = G[6],
    G6 = G[7],
    G7 = G[8],
    G8 = G[9],
    Gm1 = G[0];
export const Gs = notes(8);
export const Gs0 = Gs[1],
    Gs1 = Gs[2],
    Gs2 = Gs[3],
    Gs3 = Gs[4],
    Gs4 = Gs[5],
    Gs5 = Gs[6],
    Gs6 = Gs[7],
    Gs7 = Gs[8],
    Gsm1 = Gs[0];
export const Ab = Gs;
export const Ab0 = Ab[1],
    Ab1 = Ab[2],
    Ab2 = Ab[3],
    Ab3 = Ab[4],
    Ab4 = Ab[5],
    Ab5 = Ab[6],
    Ab6 = Ab[7],
    Ab7 = Ab[8],
    Abm1 = Ab[0];
export const A = notes(9);
export const A0 = A[1],
    A1 = A[2],
    A2 = A[3],
    A3 = A[4],
    A4 = A[5],
    A5 = A[6],
    A6 = A[7],
    A7 = A[8],
    Am1 = A[0];
export const As = notes(10);
export const As0 = As[1],
    As1 = As[2],
    As2 = As[3],
    As3 = As[4],
    As4 = As[5],
    As5 = As[6],
    As6 = As[7],
    As7 = As[8],
    Asm1 = As[0];
export const Bb = As;
export const Bb0 = Bb[1],
    Bb1 = Bb[2],
    Bb2 = Bb[3],
    Bb3 = Bb[4],
    Bb4 = Bb[5],
    Bb5 = Bb[6],
    Bb6 = Bb[7],
    Bb7 = Bb[8],
    Bbm1 = Bb[0];
export const B = notes(11);
export const B0 = B[1],
    B1 = B[2],
    B2 = B[3],
    B3 = B[4],
    B4 = B[5],
    B5 = B[6],
    B6 = B[7],
    B7 = B[8],
    Bm1 = B[0];
export const Bs = C;
export const Bs0 = Bs[1],
    Bs1 = Bs[2],
    Bs2 = Bs[3],
    Bs3 = Bs[4],
    Bs4 = Bs[5],
    Bs5 = Bs[6],
    Bs6 = Bs[7],
    Bs7 = Bs[8],
    Bs8 = Bs[9],
    Bsm1 = Bs[0];
export const O = -999;

export const quarterTone = 0.25;
export const thirdTone = 0.333;
export const oneCent = 0.01;
export const tenCent = 0.1;
